### ISSUE TITLE
Use torrent-stream instead of peerflix

### ISSUE THREAD

**Issue by kicumkicum** [torrent-proxy/torrent-proxy#4]
Нужно избавиться от запуска peerflix'а и реализовать необходимый функционал используя torrent-stream.
А именно:
- [x] Скачивание раздачи по магнету
- [x] Стриминг раздачи
- [ ] Остановка скачивания с удалением закаченного (?)

**Comment by reeFridge** [comment]
задача решается в рамках модуля [http-streaming-server](https://github.com/reeFridge/http-streaming-server)

**Comment by reeFridge** [comment]
created pr #6 related to this issue

**Comment by kicumkicum** [comment]
Use bt-stream instead of both
